// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// isometricTrans
SEXP isometricTrans(NumericVector x, double epsilon);
RcppExport SEXP econophysics_isometricTrans(SEXP xSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    __result = Rcpp::wrap(isometricTrans(x, epsilon));
    return __result;
END_RCPP
}
// funcPlanarTest
int funcPlanarTest(Rcpp::NumericMatrix edgelist, int VNum);
RcppExport SEXP econophysics_funcPlanarTest(SEXP edgelistSEXP, SEXP VNumSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type edgelist(edgelistSEXP);
    Rcpp::traits::input_parameter< int >::type VNum(VNumSEXP);
    __result = Rcpp::wrap(funcPlanarTest(edgelist, VNum));
    return __result;
END_RCPP
}
// unweightVisibilityGraph
SEXP unweightVisibilityGraph(NumericVector x);
RcppExport SEXP econophysics_unweightVisibilityGraph(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(unweightVisibilityGraph(x));
    return __result;
END_RCPP
}
// weightedVisibilityGraph
SEXP weightedVisibilityGraph(NumericVector x);
RcppExport SEXP econophysics_weightedVisibilityGraph(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(weightedVisibilityGraph(x));
    return __result;
END_RCPP
}
