# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' adaptive model for CoViaR
#' @export
#' @param k 
#' @param THETA
#' @param BETA
#' @param y
#' @return a list
caviar_ADAPTIVE <- function(K, THETA, BETA, y, empiricalQuantile, VaR, RowsOfy, varPredict) {
    .Call(`_econophysics_caviar_ADAPTIVE`, K, THETA, BETA, y, empiricalQuantile, VaR, RowsOfy, varPredict)
}

#' Asyomptic slope model for CoViaR
#' @export
#' @param BETA
#' @param y
#' @return a list
caviar_AS <- function(BETA, y, empiricalQuantile, VaR, RowsOfy, varPredict) {
    .Call(`_econophysics_caviar_AS`, BETA, y, empiricalQuantile, VaR, RowsOfy, varPredict)
}

#' GARCH model for CoViaR
#' @export
#' @param BETA
#' @param y
#' @return a list
caviar_GARCH <- function(BETA, y, empiricalQuantile, VaR, RowsOfy, varPredict) {
    .Call(`_econophysics_caviar_GARCH`, BETA, y, empiricalQuantile, VaR, RowsOfy, varPredict)
}

#' SAV  model for CoViaR
#' @export
#' @param BETA
#' @param y
#' @return a list
caviar_SAV <- function(BETA, y, empiricalQuantile, VaR, RowsOfy, varPredict) {
    .Call(`_econophysics_caviar_SAV`, BETA, y, empiricalQuantile, VaR, RowsOfy, varPredict)
}

#' convert a data.frame to list
#'@export
#'@param x the dataframe to be converted
#'@return an list
df2list <- function(x) {
    .Call(`_econophysics_df2list`, x)
}

#'Function to get the edgelist form a time series
#'@export
#'@param x a numeric vector convert from a time series
#'@param epsilon the threshold
#'@return a edgelist dataframe with weights with 2 columns
#'@references Geometrical invariability of transformation between a time series and a complex network, PHYSICAL REVIEW E 90, 012804 (2014)
isometricTrans <- function(x, epsilon) {
    .Call(`_econophysics_isometricTrans`, x, epsilon)
}

#' Test a graph is planar or not
#'@export
#'@param edgelist a edgelist dataframe without edge weights
#'@param VNum vertex number of a graph which related to the edgelist
#'@return FALSE OR TRUE
funcPlanarTest <- function(edgelist, VNum) {
    .Call(`_econophysics_funcPlanarTest`, edgelist, VNum)
}

#' Function to get the edgelist form a time series
#'@export
#'@param x a numeric vector convert from a time series
#'@return a edgelist dataframe without weights with 2 columns
unweightVisibilityGraph <- function(x) {
    .Call(`_econophysics_unweightVisibilityGraph`, x)
}

#'Function to get the edgelist form a time series
#'@export
#'@param x a numeric vector convert from a time series
#'@return a edgelist dataframe with weights with 3 columns
#'@references "From time series to complex networks:The visibility graph,4972–4975, PNAS, April 1, 2008, vol. 105, no. 13"
weightedVisibilityGraph <- function(x) {
    .Call(`_econophysics_weightedVisibilityGraph`, x)
}

